esphome:
  name: ${device_name}
  friendly_name: ${nice_name}

logger:

api:
  on_client_connected:
    - logger.log: "API client connected!"
    - lvgl.page.show: main_page
  on_client_disconnected:
    - logger.log: "API client disconnected!"
    - lvgl.page.show: loading_page

ota:
  platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

captive_portal:
