esphome:
  name: ${device_name}
  friendly_name: ${nice_name}

logger:

api:
  id: ha_api
  on_client_connected:
    - if:
        condition:
          lambda: 'return client_info.find("Home Assistant") != std::string::npos;'
        then:
          - logger.log: "API client connected!"
          - lvgl.page.show: main_page

  on_client_disconnected:
    - if:
        condition:
          lambda: "return !id(ha_api).is_connected(true);"
        then:
          - logger.log: "API client disconnected!"
          - lvgl.page.show: loading_page

interval:
  - interval: 60s
    then:
      - if:
          condition:
            api.connected:
          then:
            - logger.log: "API connected, ensuring main_page is shown"
            - lvgl.page.show: main_page
          else:
            - logger.log: "API disconnected, ensuring loading_page is shown"
            - lvgl.page.show: loading_page

ota:
  platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

captive_portal:
