esphome:
  min_version: 2025.7.0

esp32:
  board: esp32dev
  framework:
    type: arduino

preferences:
  flash_write_interval: 5min

# i2c:
#   - sda: 27
#     scl: 22

# sensor:
#   - platform: adc
#     pin: 34
#     name: "Brightness"
#     update_interval: 60s

#-------------------------------------------
# Backlight
#-------------------------------------------
output:
  - platform: ledc
    pin: 21
    id: gpio_backlight_pwm
  - id: output_red
    platform: ledc
    pin: 4
    inverted: true
  - id: output_green
    platform: ledc
    pin: 16
    inverted: true
  - id: output_blue
    platform: ledc
    pin: 17
    inverted: true

light:
  - platform: monochromatic # Define a monochromatic, dimmable light for the backlight
    output: gpio_backlight_pwm
    name: Display Backlight
    icon: mdi:lightbulb-on
    id: display_backlight
    restore_mode: ALWAYS_ON
  - platform: rgb
    id: rgb_led
    name: RGB LED
    red: output_red
    green: output_green
    blue: output_blue
    restore_mode: ALWAYS_OFF

spi:
  - id: tft
    clk_pin: GPIO14
    mosi_pin: GPIO13
    miso_pin: GPIO12
  - id: touch
    clk_pin: GPIO25
    mosi_pin: GPIO32
    miso_pin: GPIO39

touchscreen:
  - id: my_touchscreen
    platform: xpt2046
    spi_id: touch
    cs_pin: 33
    interrupt_pin: 36
    threshold: 400
    calibration:
      x_min: 180
      x_max: 3800
      y_min: 240
      y_max: 3860
    transform:
      mirror_x: true
    on_touch:
      then:
        # - if:
        #     condition: lvgl.is_paused
        #     then:
        - light.turn_on:
            id: display_backlight
    on_release:
      then:
        - lvgl.resume
        - lvgl.widget.redraw

# display:
#   - id: my_display
#     platform: ili9xxx
#     model: ILI9341
#     spi_id: tft
#     cs_pin: GPIO15
#     dc_pin: GPIO2
#     invert_colors: true # original used to be false
#     color_palette: 8BIT # added this line
#     update_interval: never
#     auto_clear_enabled: false
#     # transform: # added this line
#     #   swap_xy: true
#     #   mirror_x: false
#     dimensions: #added this line
#       height: 320
#       width: 240

display:
  - id: my_display
    platform: ili9xxx
    color_palette: 8BIT
    model: ST7789V
    spi_id: tft
    cs_pin:
      number: GPIO15
      ignore_strapping_warning: true
    dc_pin:
      number: GPIO2
      ignore_strapping_warning: true
    invert_colors: false
    update_interval: never
    auto_clear_enabled: false
    # transform:
    #   swap_xy: true
    #   mirror_x: true
    dimensions:
      width: ${width}
      height: ${height}

lvgl:
  buffer_size: 25%
